export PATH="$PATH:/home/skaaj/Applications/flutter/bin"
export PATH="$PATH:/home/skaaj/Applications/sbt/sbt-1.3.13/bin"
export PATH="$PATH:/usr/lib/jvm/java-11-openjdk-amd64/bin"
export PATH="$PATH:/opt/idea-IC-202.7660.26/bin"
export PATH="$PATH:/home/skaaj/Applications/mongodb-shell/bin"
export PATH="$PATH:/home/skaaj/Applications/anaconda3/bin"
export PATH="$PATH:/home/skaaj/.config/custom/bin"
